### ISSUE TITLE
GSPC Paper - Figma (Request by our UIUX: Daniel & Che Wan)

### ISSUE THREAD

**Issue by Ac3ranJr1** [R-D-Theta-Edge/.github#100]
https://www.figma.com/pricing/#features
- nak Professional Plan, untuk dua orang (2 account)
- benefit why to choose figma: ease of use in term of the end-user support
- Why no longer use Adobe XD - XD under maintenance mode, Adobe stop end user support and new user (designer & developer) cannot install.

https://www.uxpin.com/pricing

https://support.invisionapp.com/docs/plans-pricing

**Comment by Ac3ranJr1** [comment]
Zaimah, kindly assist as discussed

**Comment by Ac3ranJr1** [comment]
Nana, please refer to the above matters, and kindly take over this task of preparing GSPC paper for us to procure subscription for FIgma, as requested by Daniel & Che wan.

**Comment by nanahamzah** [comment]
Waiting for Procurement to review, if all ok, i'll proceed with getting approval. Thanks
