### ISSUE TITLE
SakuPay: POS System

### ISSUE THREAD

**Issue by Ac3ranJr1** [R-D-Theta-Edge/.github#11]
SakuPay POS system development is currently on hold as at 28 March due to the wait for the new senior developer to be onboard onto this project. 
The plan is to have the business processes and steps along with the user story to be shared by the new developer on the POS system. 
The above actions is expected to run after Harry Raya Aidilfitri 2024.

**Comment by ridzuwary-theta-edge** [comment]
Senior developer has been onboarded. Project has begun.
