### ISSUE TITLE
GSPC - POS System Devices (Android Tablet & Barcode Scanner) & Receipt Paper Rolls

### ISSUE THREAD

**Issue by nanahamzah** [R-D-Theta-Edge/.github#122]
GSPC paper for POS System Testing and Development 

Document link: https://thetaedgebhd.sharepoint.com/:w:/s/ThetaInnovation/EVZjArNs2gBEiEIIEs2793YBi5DQnwhdJSBe5x55PdEdUg?e=gcuFV0

Status: Waiting for Procurement to share RFQ

**Comment by ThetaInno** [comment]
GSPC paper has been prepared and we attended GSPC seating on September 30th, and the Committee has decided to hold the paper until next year. Their reasoning is that we can continue using the POS system provided by Ogoshop for our testing.
