### ISSUE TITLE
[SAKUPAY] Onboarding Merchant (NGO) Pertubuhan Kebajikan Darul Aitam Bukit Pegoh

### ISSUE THREAD

**Issue by nanahamzah** [R-D-Theta-Edge/.github#126]
Management has decided to support the ‘PROGRAM JIWA MURNI SEMPENA SAMBUTAN HARI MUBARAK NEGERI MELAKA’ organise by Majlis Bekas Wakil Rakyat Negeri Melaka on 20 July 2024.  The event will be graced by YAB Datuk Seri Utama Ab Rauf bin Yusoh (Ketua Menteri Melaka).
 
Further to DCEO’s mandate, here are the proposals :
 
a.           To purchase 1 table (Hang Kasturi Package) : RM10,000 – Budget : SCD
b.           Donation /contribution of RM5,000 (via SakuPay) to Pertubuhan Kebajikan tlarul'Aitam Bukit Pegoh, Pernu, Melaka (No. Pendaftaran Pertubuhan : PPM-023-04-13082018) – Budget : Innovation/SakuPay
              **SakuPay team need to engage with this organisation for onboarding process**
c.           Hand over a mock cheque to YAB on that night. 
 
Status: Nana is currently waiting for the NGO to share all the supporting documents.

**Comment by nanahamzah** [comment]
Pending supporting docs from the NGO...

**Comment by ThetaInno** [comment]
Darul Aitam has provided all the necessary documents, and on October 15th, Fasspay successfully onboarded Darul Aitam as a merchant.
