### ISSUE TITLE
Department FTE, Org Chart & Delegation Workflow

### ISSUE THREAD

**Issue by nichleegc6929** [R-D-Theta-Edge/.github#234]
Attached to this are the Department’s current Full-time equivalent, the organization chart, and the delegation workflow for the Innovation department. It was initially conceptualized by Wary and from there, we decided to have it this recorded as part of our future reference back in April this year (i.e. 2024).

**Comment by nichleegc6929** [comment]
Innovation FTE:
https://thetaedgebhd.sharepoint.com/:x:/s/ThetaInnovation/EWiaCokLU3BPmuH1xN4ArR0B8-tMRiM9JhlMwPOWfAo2ug?e=gfVtBD

Innovation Org-chart:
https://thetaedgebhd.sharepoint.com/:p:/s/ThetaInnovation/EXbkO24mBY5MvxgyqDdwtLwBWfdiwAj_sDKP_cMHdjIHMg?e=yDzrDC

Innovation delegation of work:
​https://thetaedgebhd.sharepoint.com/:p:/s/ThetaInnovation/EYpxPLZTOblLg-g4S2NY6YwBy8kI1hHv_q6gs507hUBgLA?e=lNAjgC

**Comment by nichleegc6929** [comment]
These documents was shared and presented briefly to the internal audit team on 31st July 2024 at 11.20am

**Comment by nichleegc6929** [comment]
New org chart as at 7th August 2024:[
](https://thetaedgebhd.sharepoint.com/:f:/s/ThetaInnovation/EgHEgYTjzDJDjiqNZhQEMuEBueSFmPfG79vOe8F7qnLNrg?e=Fknuik)

**Comment by buttercup-404** [comment]
done
