### ISSUE TITLE
GIWC Slide

### ISSUE THREAD

**Issue by nanahamzah** [R-D-Theta-Edge/.github#241]

**Comment by nanahamzah** [comment]
Already presented to Effie the GIWC slide with Alim, however, there are some amendments and points need to be included. Next review this Friday.

**Comment by nichleegc6929** [comment]
Need to add on one slide in the GIWC deck: under Sakupay section - Integrating eKupon into Sakupay
more information on eKupon: https://www.e-kupon.com.my/

**Comment by nanahamzah** [comment]
Okie noted

**Comment by nanahamzah** [comment]
Completed, here's the link for 6th Theta GIWC slide:
https://thetaedgebhd.sharepoint.com/:p:/s/ThetaInnovation/EUDV_Bhu0PtGtwufj3e966UBCK5cr81NKdrqR1Zq2cjJPQ?e=EK2I99
