### ISSUE TITLE
Dashboard Zon - Bootstrap 3.3.7 < 4.1.2 Cross-Site Scripting

### ISSUE THREAD

**Issue by ayienyusof** [R-D-Theta-Edge/.github#273]

**Comment by ayienyusof** [comment]
FIRMUS recommends TH to upgrade the Bootstrap to the latest and most stable version of 5.3 or later.

**Comment by nurfadlan** [comment]
- update to 3.4.1 instead
- bootstrap 3 cannot directly update to 4. different implementation
