### ISSUE TITLE
[NEO HM WORKSHOP] Design Task for Neo HM Workshop Poster and Agenda

### ISSUE THREAD

**Issue by nanahamzah** [R-D-Theta-Edge/.github#292]
Hi Ciwan, since @DanielMuhalli is on EL, I need your help to design the poster and agenda for our upcoming Neo HM workshop. Below is the details and the draft agenda. I will share the finalized version once it’s confirmed.

Tajuk: Perbincangan Keperluan Pengguna Sistem SOY dan Penempatan Jemaah di Madinah
Tempat: Bilik Anggerik, Tingkat 1, Theta Edge Berhad
Tarikh: 7 Oktober 2024 (Isnin)
Masa: 8.30 am - 5.30 pm

8.30 - 9.00 : Pendaftaran Peserta
9.00 - 9.30 : Sarapan Pagi 
9.30 - 12.30 : Perbincangan Sesi 1
12.30 -2.00  : Makan Tengahari 
2.00 - 4.00 : Perbincangan Sesi 2
4.00 - 4.30 :  Makan Petang 
4.30 - 5.15 : Perbincangan & Soal Jawab 
5.15 – 5.30 : Bersurai 

Deadline: Next Tuesday

**Comment by CwMi** [comment]
Size: 16:9 / 4:3 - Presentation Size
Purpose: Display during the workshop

**Comment by CwMi** [comment]
![Poster](https://github.com/user-attachments/assets/1a8a10fd-2b98-4861-938b-9ab0beff4bf3)
![Tentatif](https://github.com/user-attachments/assets/80d45e0b-9a2b-4ef9-a32f-fc5c1826213c)

Media includes
Main Poster - 1x - for Display
Tentatif - 1x - for Display
