### ISSUE TITLE
Submit team KPI for 2024

### ISSUE THREAD

**Issue by ridzuwary-theta-edge** [R-D-Theta-Edge/.github#3]
Concurrently prepare Group Balanced Scorecard and Individual KPI

**Comment by Ac3ranJr1** [comment]
Innovation team KPI have been discussed between Alim, Wary, Hijri and Nick on 28 March 2024.
Individual KPI to be completed by 3pm, 3 April 2024.

https://thetaedgebhd.sharepoint.com/:x:/s/ThetaInnovation/EZHALJRlncpLjHIolkk3HZ4BvL63_STMSDp1_2-VMBS_fw?e=3g6eeu
