### ISSUE TITLE
[SAKUPAY] Request for Social Media Links Update on SakuPay Website

### ISSUE THREAD

**Issue by ThetaInno** [R-D-Theta-Edge/.github#72]
Hi Ameer! I wanted to request an update to the social media links on the SakuPay website. Currently, the links to our Facebook, LinkedIn, Instagram, and Twitter pages are not pointing to our latest profiles. Here are the updated links that need to be implemented:

Facebook: [https://www.facebook.com/profile.php?id=61555633619215](url)
LinkedIn: [linkedin.com/company/sakupay](url)
Instagram: [https://www.instagram.com/sakupayofficial?igsh=MTczdTNsY2Jhamx1OA==](url)
Twitter: If possible, remove the Twitter icon bcs we dont have Twitter acc for SakuPay.

Could you please update these links on the SakuPay website when you have some time? Your help in ensuring our visitors are directed to the correct pages is greatly appreciated. 

![Screenshot (46)](https://github.com/R-D-Theta-Edge/.github/assets/167965615/82bd2161-a4a1-4312-88bd-707af32dcd48)

Thanks Ameer!

**Comment by AmeerFaisalAdanan** [comment]
done. please check site for review
